version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo-replica
    ports:
      - "27030:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: